version: '3'
services:
  redis:
    image: "redis:5.0.5"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    container_name: redis
    networks:
      - saas-starter-net
    volumes:
      - redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  database:
    image: "postgres:11.4-alpine"
    hostname: database
    container_name: postgres
    networks:
      - saas-starter-net
    ports:
      - 5533:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  saas-starter-net:

volumes:
  redis-data:
  db-data:
