version: '3'
services:
  database:
    image: "postgres:11.4-alpine"
    hostname: saas_database
    container_name: postgres
    networks:
      - saas-starter-net
    ports:
      - 5533:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  saas-starter-net:

volumes:
  db-data:
