version: '3.9'
services:
  database:
    image: "postgres:14.3-alpine"
    hostname: db
    container_name: postgres
    networks:
      - app-network
    ports:
      - 55432:5432
    volumes:
      - ./docker/volumes/pgsql/data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  db-data:
