version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v2-gradle-cache-{{ checksum "build.gradle.all" }}
      - run:
          name: Init gradle wrapper
          command: gradle wrapper
      - run:
          name: Run tests & Generate code coverage && perform static code analysis
          command: ./gradlew jacocoRootReport detekt
      - run:
          name: Generate cache key
          command: cat $(find **/build.gradle) > build.gradle.all
      - save_cache:
          name: Save gradle wrapper cache
          paths:
            - ~/.gradle/caches/
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          name: Save gradle cache to cache
          paths:
            - ~/.gradle/caches/
          key: gradle-cache-{{ checksum "build.gradle.all" }}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - store_artifacts:
          path: build/libs
      - codecov/upload:
          file: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
workflows:
  version: 2
  workflow:
    jobs:
      - build
